### ISSUE TITLE
有谁在24G的显存上，把CogAgent跑起来么？

### ISSUE THREAD

**Issue by NielHung** [THUDM/CogAgent#1]
下面是我测试的过程：
hf版本：
python cli_demo_hf.py --fp16 --quant 4 （推理出错）
python cli_demo_hf.py --fp16 （加载62%崩溃）
python cli_demo_hf.py --fp16 --quant 8（不支持参数值8，看源码只能支持4）

sat版本：
# In SAT version，--quant should be used with --fp16
python cli_demo_sat.py --bf16  --stream_chat （加载过程提示gpu不够）
python cli_demo_sat.py --bf16 --quant 8 --stream_chat （加载过程死机）
python cli_demo_sat.py --bf16 --quant 4 --stream_chat（加载过程死机）

**Comment by 17603127956** [comment]
> python cli_demo_hf.py --fp16 --quant 8（

请问最后 24g 卡 跑起来了么？

**Comment by NielHung** [comment]
> > python cli_demo_hf.py --fp16 --quant 8（
> 
> 请问最后 24g 卡 跑起来了么？

算是跑起来了，固定提问格式还可以
