### ISSUE TITLE
24g 显存的卡是否会支持？

### ISSUE THREAD

**Issue by 17603127956** [THUDM/CogAgent#10]
### Feature request  / 功能建议

开发者您好，目前看文档里支持最低显存 29g，但是手头只有 24g 显存的显卡和 22g 显存的显卡，请问后续是否会支持此类型的显卡？非常感谢

### Motivation / 动机

个人开发者，手头资源有限，希望开发者可以支持！

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
目前可以使用Int8的载入方案，占用15G左右

**Comment by amumu96** [comment]
> 目前可以使用Int8的载入方案，占用15G左右。我已经更新上了Int8的代码，就一行

请问模型是否支持多卡推理？

**Comment by zRzRzRzRzRzRzR** [comment]
使用device map = auto可以尝试一下，通常是支持的
