### ISSUE TITLE
推理功能是否用到ReST-MCTS？

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/CogAgent#8]
推理和反思功能是否用到了ReST-MCTS呢？或是其它的实现有用到ReST-MCTS呢？

**Comment by zRzRzRzRzRzRzR** [comment]
单次推理中没有进行反思，而是根据用户的输入（或者用脚本实现输入）后作出下一步规划

**Comment by wenyihong** [comment]
1. 目前的模型版本还没有基于反思进行训练和推理，同时我们也关注到LLM乃至GUI Agent上使用反思都得到了不错的提升。
2. 关于反思和ReST-MCTS，在GUI Agent领域的一大问题是，受限于数据采集的难度和当前模型的性能，难以构建良好的数据和Reward。与此同时，这一版CogAgent的GUI Agent能力有明显的提升，我们认为是一个良好的基座模型，可以基于此进行相关算法的研发、数据构造。
3. 是
